sudo: required

services:
  - docker

script:
  - docker build -t ijun/wndr4300-lede-sdk .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ijun/wndr4300-lede-sdk;
    fi

